const teamsData = [
    {
        "id": "csk",
        "name": "Chennai Super Kings",
        "color": "#F9CD05",
        "players": [
            { "id": "csk_1", "name": "Ruturaj Gaikwad", "role": "Batter", "isOverseas": false, "isCaptain": true },
            { "id": "csk_2", "name": "Dewald Brevis", "role": "Batter", "isOverseas": true },
            { "id": "csk_3", "name": "Ayush Mhatre", "role": "Batter", "isOverseas": false },
            { "id": "csk_4", "name": "Matthew Short", "role": "Batter", "isOverseas": true },
            { "id": "csk_5", "name": "Sarfaraz Khan", "role": "Batter", "isOverseas": false },
            { "id": "csk_6", "name": "Shivam Dube", "role": "All-rounder", "isOverseas": false },
            { "id": "csk_7", "name": "Ramakrishna Ghosh", "role": "All-rounder", "isOverseas": false },
            { "id": "csk_8", "name": "Jamie Overton", "role": "All-rounder", "isOverseas": true },
            { "id": "csk_9", "name": "Anshul Kamboj", "role": "All-rounder", "isOverseas": false },
            { "id": "csk_10", "name": "Prashant Veer", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "csk_11", "name": "Zakary Foulkes", "role": "All-rounder", "isOverseas": true },
            { "id": "csk_12", "name": "Aman Khan", "role": "All-rounder", "isOverseas": false },
            { "id": "csk_13", "name": "MS Dhoni", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "csk_14", "name": "Urvil Patel", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "csk_15", "name": "Sanju Samson", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "csk_16", "name": "Kartik Sharma", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "csk_17", "name": "Shreyas Gopal", "role": "Spin Bowler", "isOverseas": false },
            { "id": "csk_18", "name": "Khaleel Ahmed", "role": "Fast Bowler", "isOverseas": false },
            { "id": "csk_19", "name": "Gurjapneet Singh", "role": "Fast Bowler", "isOverseas": false },
            { "id": "csk_20", "name": "Mukesh Choudhary", "role": "Fast Bowler", "isOverseas": false },
            { "id": "csk_21", "name": "Noor Ahmad", "role": "Spin Bowler", "isOverseas": true },
            { "id": "csk_22", "name": "Akeal Hosein", "role": "Spin Bowler", "isOverseas": true },
            { "id": "csk_23", "name": "Matt Henry", "role": "Fast Bowler", "isOverseas": true },
            { "id": "csk_24", "name": "Rahul Chahar", "role": "Spin Bowler", "isOverseas": false },
            { "id": "csk_25", "name": "Spencer Johnson", "role": "Fast Bowler", "isOverseas": true }
        ]
    },
    {
        "id": "dc",
        "name": "Delhi Capitals",
        "color": "#00008B",
        "players": [
            { "id": "dc_1", "name": "Karun Nair", "role": "Batter", "isOverseas": false },
            { "id": "dc_2", "name": "Nitish Rana", "role": "Batter", "isOverseas": false },
            { "id": "dc_3", "name": "Sameer Rizvi", "role": "Batter", "isOverseas": false },
            { "id": "dc_4", "name": "David Miller", "role": "Batter", "isOverseas": true },
            { "id": "dc_5", "name": "Pathum Nissanka", "role": "Batter", "isOverseas": true },
            { "id": "dc_6", "name": "Sahil Parakh", "role": "Batter", "isOverseas": false },
            { "id": "dc_7", "name": "Prithvi Shaw", "role": "Batter", "isOverseas": false },
            { "id": "dc_8", "name": "Ashutosh Sharma", "role": "All-rounder", "isOverseas": false },
            { "id": "dc_9", "name": "Axar Patel", "role": "All-rounder", "isOverseas": false, "isCaptain": true },
            { "id": "dc_10", "name": "Ajay Jadav Mandal", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "dc_11", "name": "Madhav Tiwari", "role": "All-rounder", "isOverseas": false },
            { "id": "dc_12", "name": "Tripurana Vijay", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "dc_13", "name": "Auqib Nabi Dar", "role": "All-rounder", "isOverseas": false },
            { "id": "dc_14", "name": "Abishek Porel", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "dc_15", "name": "KL Rahul", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "dc_16", "name": "Tristan Stubbs", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "dc_17", "name": "Dushmantha Chameera", "role": "Fast Bowler", "isOverseas": true },
            { "id": "dc_18", "name": "Kuldeep Yadav", "role": "Spin Bowler", "isOverseas": false },
            { "id": "dc_19", "name": "Mukesh Kumar", "role": "Fast Bowler", "isOverseas": false },
            { "id": "dc_20", "name": "T Natarajan", "role": "Fast Bowler", "isOverseas": false },
            { "id": "dc_21", "name": "Vipraj Nigam", "role": "Spin Bowler", "isOverseas": false },
            { "id": "dc_22", "name": "Mitchell Starc", "role": "Fast Bowler", "isOverseas": true },
            { "id": "dc_23", "name": "Lungi Ngidi", "role": "Fast Bowler", "isOverseas": true },
            { "id": "dc_24", "name": "Kyle Jamieson", "role": "Fast Bowler", "isOverseas": true }
        ]
    },
    {
        "id": "gt",
        "name": "Gujarat Titans",
        "color": "#1B2133",
        "players": [
            { "id": "gt_1", "name": "Shubman Gill", "role": "Batter", "isOverseas": false, "isCaptain": true },
            { "id": "gt_2", "name": "M Shahrukh Khan", "role": "Batter", "isOverseas": false },
            { "id": "gt_3", "name": "Sai Sudharsan", "role": "Batter", "isOverseas": false },
            { "id": "gt_4", "name": "Nishant Sindhu", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "gt_5", "name": "Rashid Khan", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "gt_6", "name": "Manav Suthar", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "gt_7", "name": "Rahul Tewatia", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "gt_8", "name": "Washington Sundar", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "gt_9", "name": "Arshad Khan", "role": "All-rounder", "isOverseas": false },
            { "id": "gt_10", "name": "Ravisrinivasan Sai Kishore", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "gt_11", "name": "Jason Holder", "role": "All-rounder", "isOverseas": true },
            { "id": "gt_12", "name": "Anuj Rawat", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "gt_13", "name": "Jos Buttler", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "gt_14", "name": "Kumar Kushagra", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "gt_15", "name": "Glenn Phillips", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "gt_16", "name": "Tom Banton", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "gt_17", "name": "Gurnoor Brar", "role": "Fast Bowler", "isOverseas": false },
            { "id": "gt_18", "name": "Mohammed Siraj", "role": "Fast Bowler", "isOverseas": false },
            { "id": "gt_19", "name": "Prasidh Krishna", "role": "Fast Bowler", "isOverseas": false },
            { "id": "gt_20", "name": "Kagiso Rabada", "role": "Fast Bowler", "isOverseas": true },
            { "id": "gt_21", "name": "Jayant Yadav", "role": "Spin Bowler", "isOverseas": false },
            { "id": "gt_22", "name": "Ishant Sharma", "role": "Fast Bowler", "isOverseas": false },
            { "id": "gt_23", "name": "Ashok Sharma", "role": "Fast Bowler", "isOverseas": false },
            { "id": "gt_24", "name": "Prithvi Raj Yarra", "role": "Fast Bowler", "isOverseas": false },
            { "id": "gt_25", "name": "Luke Wood", "role": "Fast Bowler", "isOverseas": true }
        ]
    },
    {
        "id": "kkr",
        "name": "Kolkata Knight Riders",
        "color": "#3A225D",
        "players": [
            { "id": "kkr_1", "name": "Ajinkya Rahane", "role": "Batter", "isOverseas": false, "isCaptain": true },
            { "id": "kkr_2", "name": "Manish Pandey", "role": "Batter", "isOverseas": false },
            { "id": "kkr_3", "name": "Rovman Powell", "role": "Batter", "isOverseas": true },
            { "id": "kkr_4", "name": "Angkrish Raghuvanshi", "role": "Batter", "isOverseas": false },
            { "id": "kkr_5", "name": "Rinku Singh", "role": "Batter", "isOverseas": false },
            { "id": "kkr_6", "name": "Finn Allen", "role": "Batter", "isOverseas": true },
            { "id": "kkr_7", "name": "Rahul Tripathi", "role": "Batter", "isOverseas": false },
            { "id": "kkr_8", "name": "Sarthak Ranjan", "role": "Batter", "isOverseas": false },
            { "id": "kkr_9", "name": "Ramandeep Singh", "role": "All-rounder", "isOverseas": false },
            { "id": "kkr_10", "name": "Anukul Roy", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "kkr_11", "name": "Cameron Green", "role": "All-rounder", "isOverseas": true },
            { "id": "kkr_12", "name": "Rachin Ravindra", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "kkr_13", "name": "Sunil Narine", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "kkr_14", "name": "Daksh Kamra", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "kkr_15", "name": "Tim Seifert", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "kkr_16", "name": "Tejasvi Dahiya", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "kkr_17", "name": "Vaibhav Arora", "role": "Fast Bowler", "isOverseas": false },
            { "id": "kkr_18", "name": "Umran Malik", "role": "Fast Bowler", "isOverseas": false },
            { "id": "kkr_19", "name": "Varun Chakaravarthy", "role": "Spin Bowler", "isOverseas": false },
            { "id": "kkr_20", "name": "Prashant Solanki", "role": "Spin Bowler", "isOverseas": false },
            { "id": "kkr_21", "name": "Kartik Tyagi", "role": "Fast Bowler", "isOverseas": false },
            { "id": "kkr_22", "name": "Matheesha Pathirana", "role": "Fast Bowler", "isOverseas": true },
            { "id": "kkr_23", "name": "Blessing Muzarabani", "role": "Fast Bowler", "isOverseas": true },
            { "id": "kkr_24", "name": "Saurabh Dubey", "role": "Fast Bowler", "isOverseas": false },
            { "id": "kkr_25", "name": "Navdeep Saini", "role": "Fast Bowler", "isOverseas": false }
        ]
    },
    {
        "id": "lsg",
        "name": "Lucknow Super Giants",
        "color": "#0057E2",
        "players": [
            { "id": "lsg_1", "name": "Himmat Singh", "role": "Batter", "isOverseas": false },
            { "id": "lsg_2", "name": "Aiden Markram", "role": "Batter", "isOverseas": true },
            { "id": "lsg_3", "name": "Akshat Raghuwanshi", "role": "Batter", "isOverseas": false },
            { "id": "lsg_4", "name": "Abdul Samad", "role": "All-rounder", "isOverseas": false },
            { "id": "lsg_5", "name": "Ayush Badoni", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "lsg_6", "name": "Arshin Kulkarni", "role": "All-rounder", "isOverseas": false },
            { "id": "lsg_7", "name": "Mitchell Marsh", "role": "All-rounder", "isOverseas": true },
            { "id": "lsg_8", "name": "Shahbaz Ahmed", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "lsg_9", "name": "Arjun Sachin Tendulkar", "role": "All-rounder", "isOverseas": false },
            { "id": "lsg_10", "name": "Wanindu Hasaranga", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "lsg_11", "name": "Rishabh Pant", "role": "Wicketkeeper", "isOverseas": false, "isCaptain": true },
            { "id": "lsg_12", "name": "Matthew Breetzke", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "lsg_13", "name": "Nicholas Pooran", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "lsg_14", "name": "Mukul Choudhary", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "lsg_15", "name": "Josh Inglis", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "lsg_16", "name": "Akash Maharaj Singh", "role": "Fast Bowler", "isOverseas": false },
            { "id": "lsg_17", "name": "Avesh Khan", "role": "Fast Bowler", "isOverseas": false },
            { "id": "lsg_18", "name": "Mohammed Shami", "role": "Fast Bowler", "isOverseas": false },
            { "id": "lsg_19", "name": "Prince Yadav", "role": "Fast Bowler", "isOverseas": false },
            { "id": "lsg_20", "name": "Mohsin Khan", "role": "Fast Bowler", "isOverseas": false },
            { "id": "lsg_21", "name": "Digvesh Singh Rathi", "role": "Spin Bowler", "isOverseas": false },
            { "id": "lsg_22", "name": "Manimaran Siddharth", "role": "Spin Bowler", "isOverseas": false },
            { "id": "lsg_23", "name": "Mayank Prabhu Yadav", "role": "Fast Bowler", "isOverseas": false },
            { "id": "lsg_24", "name": "Anrich Nortje", "role": "Fast Bowler", "isOverseas": true },
            { "id": "lsg_25", "name": "Naman Tiwari", "role": "Fast Bowler", "isOverseas": false }
        ]
    },
    {
        "id": "mi",
        "name": "Mumbai Indians",
        "color": "#004BA0",
        "players": [
            { "id": "mi_1", "name": "Naman Dhir", "role": "Batter", "isOverseas": false },
            { "id": "mi_2", "name": "Rohit Sharma", "role": "Batter", "isOverseas": false },
            { "id": "mi_3", "name": "Suryakumar Yadav", "role": "Batter", "isOverseas": false },
            { "id": "mi_4", "name": "Tilak Varma", "role": "Batter", "isOverseas": false },
            { "id": "mi_5", "name": "Danish Malewar", "role": "Batter", "isOverseas": false },
            { "id": "mi_6", "name": "Sherfane Rutherford", "role": "All-rounder", "isOverseas": true },
            { "id": "mi_7", "name": "Hardik Pandya", "role": "All-rounder", "isOverseas": false, "isCaptain": true },
            { "id": "mi_8", "name": "Raj Bawa", "role": "All-rounder", "isOverseas": false },
            { "id": "mi_9", "name": "Will Jacks", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "mi_10", "name": "Mayank Rawat", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "mi_11", "name": "Corbin Bosch", "role": "All-rounder", "isOverseas": true },
            { "id": "mi_12", "name": "Mitchell Santner", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "mi_13", "name": "Shardul Thakur", "role": "All-rounder", "isOverseas": false },
            { "id": "mi_14", "name": "Atharva Ankolekar", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "mi_15", "name": "Robin Minz", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "mi_16", "name": "Ryan Rickelton", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "mi_17", "name": "Quinton de Kock", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "mi_18", "name": "Trent Boult", "role": "Fast Bowler", "isOverseas": true },
            { "id": "mi_19", "name": "Ashwani Kumar", "role": "Fast Bowler", "isOverseas": false },
            { "id": "mi_20", "name": "Jasprit Bumrah", "role": "Fast Bowler", "isOverseas": false },
            { "id": "mi_21", "name": "Deepak Chahar", "role": "Fast Bowler", "isOverseas": false },
            { "id": "mi_22", "name": "Mayank Markande", "role": "Spin Bowler", "isOverseas": false },
            { "id": "mi_23", "name": "AM Ghazanfar", "role": "Spin Bowler", "isOverseas": true },
            { "id": "mi_24", "name": "Raghu Sharma", "role": "Spin Bowler", "isOverseas": false },
            { "id": "mi_25", "name": "Mohammed Salahuddin Izhar", "role": "Fast Bowler", "isOverseas": false }
        ]
    },
    {
        "id": "pbks",
        "name": "Punjab Kings",
        "color": "#ED1B24",
        "players": [
            { "id": "pbks_1", "name": "Shreyas Iyer", "role": "Batter", "isOverseas": false, "isCaptain": true },
            { "id": "pbks_2", "name": "Priyansh Arya", "role": "Batter", "isOverseas": false },
            { "id": "pbks_3", "name": "Pyla Avinash", "role": "Batter", "isOverseas": false },
            { "id": "pbks_4", "name": "Harnoor Singh", "role": "Batter", "isOverseas": false },
            { "id": "pbks_5", "name": "Nehal Wadhera", "role": "Batter", "isOverseas": false },
            { "id": "pbks_6", "name": "Mitchell Owen", "role": "All-rounder", "isOverseas": true },
            { "id": "pbks_7", "name": "Musheer Khan", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "pbks_8", "name": "Shashank Singh", "role": "All-rounder", "isOverseas": false },
            { "id": "pbks_9", "name": "Marcus Stoinis", "role": "All-rounder", "isOverseas": true },
            { "id": "pbks_10", "name": "Suryansh Shedge", "role": "All-rounder", "isOverseas": false },
            { "id": "pbks_11", "name": "Cooper Connolly", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "pbks_12", "name": "Azmatullah Omarzai", "role": "All-rounder", "isOverseas": true },
            { "id": "pbks_13", "name": "Marco Jansen", "role": "All-rounder", "isOverseas": true },
            { "id": "pbks_14", "name": "Praveen Dubey", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "pbks_15", "name": "Prabhsimran Singh", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "pbks_16", "name": "Vishnu Vinod", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "pbks_17", "name": "Arshdeep Singh", "role": "Fast Bowler", "isOverseas": false },
            { "id": "pbks_18", "name": "Xavier Bartlett", "role": "Fast Bowler", "isOverseas": true },
            { "id": "pbks_19", "name": "Yuzvendra Chahal", "role": "Spin Bowler", "isOverseas": false },
            { "id": "pbks_20", "name": "Lockie Ferguson", "role": "Fast Bowler", "isOverseas": true },
            { "id": "pbks_21", "name": "Harpreet Brar", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "pbks_22", "name": "Vijaykumar Vyshak", "role": "Fast Bowler", "isOverseas": false },
            { "id": "pbks_23", "name": "Yash Thakur", "role": "Fast Bowler", "isOverseas": false },
            { "id": "pbks_24", "name": "Ben Dwarshuis", "role": "Fast Bowler", "isOverseas": true },
            { "id": "pbks_25", "name": "Vishal Nishad", "role": "Fast Bowler", "isOverseas": false }
        ]
    },
    {
        "id": "rr",
        "name": "Rajasthan Royals",
        "color": "#EA1A82",
        "players": [
            { "id": "rr_1", "name": "Shubham Dubey", "role": "Batter", "isOverseas": false },
            { "id": "rr_2", "name": "Shimron Hetmyer", "role": "Batter", "isOverseas": true },
            { "id": "rr_3", "name": "Yashasvi Jaiswal", "role": "Batter", "isOverseas": false },
            { "id": "rr_4", "name": "Vaibhav Sooryavanshi", "role": "Batter", "isOverseas": false },
            { "id": "rr_5", "name": "Aman Rao Perala", "role": "Batter", "isOverseas": false },
            { "id": "rr_6", "name": "Riyan Parag", "role": "Spin All-rounder", "isOverseas": false, "isCaptain": true },
            { "id": "rr_7", "name": "Dasun Shanaka", "role": "All-rounder", "isOverseas": true },
            { "id": "rr_8", "name": "Ravindra Jadeja", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "rr_9", "name": "Dhruv Jurel", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "rr_10", "name": "Lhuan-dre Pretorius", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "rr_11", "name": "Donovan Ferreira", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "rr_12", "name": "Ravi Singh", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "rr_13", "name": "Jofra Archer", "role": "Fast Bowler", "isOverseas": true },
            { "id": "rr_14", "name": "Nandre Burger", "role": "Fast Bowler", "isOverseas": true },
            { "id": "rr_15", "name": "Tushar Deshpande", "role": "Fast Bowler", "isOverseas": false },
            { "id": "rr_16", "name": "Kwena Maphaka", "role": "Fast Bowler", "isOverseas": true },
            { "id": "rr_17", "name": "Sandeep Sharma", "role": "Fast Bowler", "isOverseas": false },
            { "id": "rr_18", "name": "Yudhvir Singh Charak", "role": "Fast Bowler", "isOverseas": false },
            { "id": "rr_19", "name": "Vignesh Puthur", "role": "Spin Bowler", "isOverseas": false },
            { "id": "rr_20", "name": "Yash Raj Punja", "role": "Spin Bowler", "isOverseas": false },
            { "id": "rr_21", "name": "Sushant Mishra", "role": "Fast Bowler", "isOverseas": false },
            { "id": "rr_22", "name": "Ravi Bishnoi", "role": "Spin Bowler", "isOverseas": false },
            { "id": "rr_23", "name": "Brijesh Sharma", "role": "Fast Bowler", "isOverseas": false },
            { "id": "rr_24", "name": "Adam Milne", "role": "Fast Bowler", "isOverseas": true },
            { "id": "rr_25", "name": "Kuldeep Sen", "role": "Fast Bowler", "isOverseas": false }
        ]
    },
    {
        "id": "rcb",
        "name": "Royal Challengers Bengaluru",
        "color": "#EC1C24",
        "players": [
            { "id": "rcb_1", "name": "Rajat Patidar", "role": "Batter", "isOverseas": false, "isCaptain": true },
            { "id": "rcb_2", "name": "Tim David", "role": "Batter", "isOverseas": true },
            { "id": "rcb_3", "name": "Virat Kohli", "role": "Batter", "isOverseas": false },
            { "id": "rcb_4", "name": "Devdutt Padikkal", "role": "Batter", "isOverseas": false },
            { "id": "rcb_5", "name": "Jacob Bethell", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "rcb_6", "name": "Krunal Pandya", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "rcb_7", "name": "Venkatesh Iyer", "role": "All-rounder", "isOverseas": false },
            { "id": "rcb_8", "name": "Vihaan Malhotra", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "rcb_9", "name": "Romario Shepherd", "role": "All-rounder", "isOverseas": true },
            { "id": "rcb_10", "name": "Mangesh Yadav", "role": "All-rounder", "isOverseas": false },
            { "id": "rcb_11", "name": "Kanishk Chouhan", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "rcb_12", "name": "Satvik Deswal", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "rcb_13", "name": "Philip Salt", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "rcb_14", "name": "Jitesh Sharma", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "rcb_15", "name": "Jordan Cox", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "rcb_16", "name": "Abhinandan Singh", "role": "Fast Bowler", "isOverseas": false },
            { "id": "rcb_17", "name": "Josh Hazlewood", "role": "Fast Bowler", "isOverseas": true },
            { "id": "rcb_18", "name": "Rasikh Salam Dar", "role": "Fast Bowler", "isOverseas": false },
            { "id": "rcb_19", "name": "Bhuvneshwar Kumar", "role": "Fast Bowler", "isOverseas": false },
            { "id": "rcb_20", "name": "Suyash Sharma", "role": "Spin Bowler", "isOverseas": false },
            { "id": "rcb_21", "name": "Swapnil Singh", "role": "Spin Bowler", "isOverseas": false },
            { "id": "rcb_22", "name": "Nuwan Thushara", "role": "Fast Bowler", "isOverseas": true },
            { "id": "rcb_23", "name": "Jacob Duffy", "role": "Fast Bowler", "isOverseas": true },
            { "id": "rcb_24", "name": "Vicky Ostwal", "role": "Spin Bowler", "isOverseas": false }
        ]
    },
    {
        "id": "srh",
        "name": "Sunrisers Hyderabad",
        "color": "#FF822A",
        "players": [
            { "id": "srh_1", "name": "Travis Head", "role": "Batter", "isOverseas": true },
            { "id": "srh_2", "name": "Smaran Ravichandran", "role": "Batter", "isOverseas": false },
            { "id": "srh_3", "name": "Aniket Verma", "role": "Batter", "isOverseas": false },
            { "id": "srh_4", "name": "Abhishek Sharma", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "srh_5", "name": "Kamindu Mendis", "role": "All-rounder", "isOverseas": true },
            { "id": "srh_6", "name": "Nitish Kumar Reddy", "role": "All-rounder", "isOverseas": false },
            { "id": "srh_7", "name": "Liam Livingstone", "role": "Spin All-rounder", "isOverseas": true },
            { "id": "srh_8", "name": "Harsh Dubey", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "srh_9", "name": "Shivang Kumar", "role": "Spin All-rounder", "isOverseas": false },
            { "id": "srh_10", "name": "Ishan Kishan", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "srh_11", "name": "Heinrich Klaasen", "role": "Wicketkeeper", "isOverseas": true },
            { "id": "srh_12", "name": "Salil Arora", "role": "Wicketkeeper", "isOverseas": false },
            { "id": "srh_13", "name": "Brydon Carse", "role": "Fast Bowler", "isOverseas": true },
            { "id": "srh_14", "name": "Pat Cummins", "role": "Fast Bowler", "isOverseas": true, "isCaptain": true },
            { "id": "srh_15", "name": "Eshan Malinga", "role": "Fast Bowler", "isOverseas": true },
            { "id": "srh_16", "name": "Jaydev Unadkat", "role": "Fast Bowler", "isOverseas": false },
            { "id": "srh_17", "name": "Harshal Patel", "role": "Fast Bowler", "isOverseas": false },
            { "id": "srh_18", "name": "Zeeshan Ansari", "role": "Spin Bowler", "isOverseas": false },
            { "id": "srh_19", "name": "Sakib Hussain", "role": "Fast Bowler", "isOverseas": false },
            { "id": "srh_20", "name": "Onkar Tukaram Tarmale", "role": "Fast Bowler", "isOverseas": false },
            { "id": "srh_21", "name": "Amit Kumar", "role": "Spin Bowler", "isOverseas": false },
            { "id": "srh_22", "name": "Praful Hinge", "role": "Fast Bowler", "isOverseas": false },
            { "id": "srh_23", "name": "Krains Fuletra", "role": "Spin Bowler", "isOverseas": false },
            { "id": "srh_24", "name": "Shivam Mavi", "role": "Fast Bowler", "isOverseas": false },
            { "id": "srh_25", "name": "David Payne", "role": "Fast Bowler", "isOverseas": true }
        ]
    }
];
